import { PropsWithChildren } from 'react';
import type { Metadata } from 'next';

import ContextProvider from '@/store/Context';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<PropsWithChildren>) {
    return (
        <html lang="en">
            <body>
                <ContextProvider>
                    <main>{children}</main>
                </ContextProvider>
            </body>
        </html>
    );
}
